spring:
  application:
    name: user-api

server:
  port: 8012
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.11.62:8000/eureka/
  instance:
    status-page-url-path: /swagger-ui.html
logging:
  level:
      root: info
  file: logs/user-api.log
