server:
  port: 8012
spring:
  application:
    name: user-api-V1-0
  cloud:
    config:
      profile: app
      discovery:
        enabled: true
        service-id: config
      label: develop
eureka:
  client:
    serviceUrl:
      defaultZone: http://120.55.41.124:8000/eureka/
  instance:
    status-page-url-path: /swagger-ui.html
logging:
  level:
      root: info
  file: logs/user-api.log
