server:
  port: 8012
spring:
  application:
    name: user-api-v1-0
  cloud:
    config:
      profile: app
      discovery:
        enabled: true
        service-id: config
      label: master
eureka:
  client:
    healthcheck:
      enabled: true

