spring:
  application:
    name: test-api

server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://120.55.41.124:8000/eureka/
  instance:
    status-page-url-path: /swagger-ui.html
logging:
  level:
      root: info
  file: logs/test-api.log
